---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rocy.
--- DateTime: 2026/2/25 11:33
---

if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0